name: conda-pgm-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - wheel
  - setuptools
  - boost-cpp
  - eigen
  - numpy
  - pytest
  - pytest-cov
  - nlohmann_json
  - msgpack-cxx
